
BADBOY_CCLEANER = {
	"100%", -- [1]
	"<icecrown>", -- [2]
	"armor stack", -- [3]
	"armorstack", -- [4]
	"boost", -- [5]
	"community", -- [6]
	"csgo", -- [7]
	"discount", -- [8]
	"dota2", -- [9]
	"glory", -- [10]
	"heroic", -- [11]
	"hydra", -- [12]
	"key", -- [13]
	"keystone", -- [14]
	"last chance", -- [15]
	"loot", -- [16]
	"lootshare", -- [17]
	"mythic", -- [18]
	"nbc", -- [19]
	"nova", -- [20]
	"oblivion", -- [21]
	"oblivioncommunity", -- [22]
	"oblívíon", -- [23]
	"perspective", -- [24]
	"prestige", -- [25]
	"rape", -- [26]
	"run", -- [27]
	"rust", -- [28]
	"stack armor", -- [29]
	"sylvanas community", -- [30]
	"the hivemind", -- [31]
	"tradeable", -- [32]
	"twilight", -- [33]
	"vision", -- [34]
	"░", -- [35]
}
